import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './componets/header/Navbar'
// import Footer from './componets/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="grid grid-cols-1 md:grid-cols-12 p-3 md:gap-1 lg:pt-[6%] md:pt-[10%] pt-[5rem] pb-[8%] sm:ml-60">
          <div className='col-span-9'>
        {children}
        </div>
        <div className='hidden md:block md:col-span-3 pl-2 h-auto border-l-2 '>
          manish
        </div>
        </div>
         {/* <Footer/> */}
        </body>
        
    </html>
  )
}
